<?php
$error = false;
$page_title = "Registrera";

if($_SERVER['REQUEST_METHOD'] == POST){
  if( !empty($_POST['name']) && !empty($_POST['username']) && !empty($_POST['password']) ){
    $name = mysqli_real_escape_string($conn, $_POST['name']);
    $username = mysqli_real_escape_string($conn, $_POST['username']);
    $password = mysqli_real_escape_string($conn, $_POST['password']);

    $query = "SELECT * FROM users WHERE username='".$username."'";
    $result = mysqli_query($conn, $query);

    if( mysqli_num_rows($result) == 0 ){

      // this function uses autogenerated salt
      $pw_hash = password_hash($password, PASSWORD_DEFAULT);
      $session_id = session_id();

      $query = "INSERT INTO users (name, username, pw_hash, last_session) VALUES ('$name', '$username', '$pw_hash', '{$session_id}')";
      $result = mysqli_query($conn, $query);
      $id = mysqli_insert_id($conn);

      $_SESSION['user_id'] = $id;
      redirect("home");
    } else {
      $error = "Användaren ".$_POST['username']." existerar redan, välj ett annat användarnamn.";
    }
  } else {
    $error = "Du måste fylla i alla fält";
  }
}

